-- 创建数据库
CREATE DATABASE IF NOT EXISTS Ai_format DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 使用数据库
USE Ai_format;

-- 创建用户表
CREATE TABLE IF NOT EXISTS user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    password VARCHAR(32) NOT NULL,
    nickname VARCHAR(10) DEFAULT '',
    email VARCHAR(128) DEFAULT '',
    user_pic VARCHAR(128) DEFAULT '',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);